/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface AvoFactoryInterface extends utils.Interface {
  functions: {
    "avoMultiSafeBytecode()": FunctionFragment;
    "avoMultisigImpl()": FunctionFragment;
    "avoSafeBytecode()": FunctionFragment;
    "avoSafeCreationCode()": FunctionFragment;
    "avoVersionsRegistry()": FunctionFragment;
    "avoWalletImpl()": FunctionFragment;
    "computeAddress(address)": FunctionFragment;
    "computeAddressMultisig(address)": FunctionFragment;
    "deploy(address)": FunctionFragment;
    "deployMultisig(address)": FunctionFragment;
    "deployMultisigWithVersion(address,address)": FunctionFragment;
    "deployWithVersion(address,address)": FunctionFragment;
    "initialize()": FunctionFragment;
    "isAvoSafe(address)": FunctionFragment;
    "setAvoMultisigImpl(address)": FunctionFragment;
    "setAvoWalletImpl(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "avoMultiSafeBytecode"
      | "avoMultisigImpl"
      | "avoSafeBytecode"
      | "avoSafeCreationCode"
      | "avoVersionsRegistry"
      | "avoWalletImpl"
      | "computeAddress"
      | "computeAddressMultisig"
      | "deploy"
      | "deployMultisig"
      | "deployMultisigWithVersion"
      | "deployWithVersion"
      | "initialize"
      | "isAvoSafe"
      | "setAvoMultisigImpl"
      | "setAvoWalletImpl"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "avoMultiSafeBytecode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "avoMultisigImpl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "avoSafeBytecode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "avoSafeCreationCode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "avoVersionsRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "avoWalletImpl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "computeAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "computeAddressMultisig",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "deploy",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "deployMultisig",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "deployMultisigWithVersion",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "deployWithVersion",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAvoSafe",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAvoMultisigImpl",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAvoWalletImpl",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "avoMultiSafeBytecode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "avoMultisigImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "avoSafeBytecode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "avoSafeCreationCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "avoVersionsRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "avoWalletImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeAddressMultisig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployMultisig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployMultisigWithVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployWithVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAvoSafe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAvoMultisigImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAvoWalletImpl",
    data: BytesLike
  ): Result;

  events: {
    "AvoMultiSafeDeployed(address,address)": EventFragment;
    "AvoMultiSafeDeployedWithVersion(address,address,address)": EventFragment;
    "AvoSafeDeployed(address,address)": EventFragment;
    "AvoSafeDeployedWithVersion(address,address,address)": EventFragment;
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AvoMultiSafeDeployed"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "AvoMultiSafeDeployedWithVersion"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AvoSafeDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AvoSafeDeployedWithVersion"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export interface AvoMultiSafeDeployedEventObject {
  owner: string;
  avoMultiSafe: string;
}
export type AvoMultiSafeDeployedEvent = TypedEvent<
  [string, string],
  AvoMultiSafeDeployedEventObject
>;

export type AvoMultiSafeDeployedEventFilter =
  TypedEventFilter<AvoMultiSafeDeployedEvent>;

export interface AvoMultiSafeDeployedWithVersionEventObject {
  owner: string;
  avoMultiSafe: string;
  version: string;
}
export type AvoMultiSafeDeployedWithVersionEvent = TypedEvent<
  [string, string, string],
  AvoMultiSafeDeployedWithVersionEventObject
>;

export type AvoMultiSafeDeployedWithVersionEventFilter =
  TypedEventFilter<AvoMultiSafeDeployedWithVersionEvent>;

export interface AvoSafeDeployedEventObject {
  owner: string;
  avoSafe: string;
}
export type AvoSafeDeployedEvent = TypedEvent<
  [string, string],
  AvoSafeDeployedEventObject
>;

export type AvoSafeDeployedEventFilter = TypedEventFilter<AvoSafeDeployedEvent>;

export interface AvoSafeDeployedWithVersionEventObject {
  owner: string;
  avoSafe: string;
  version: string;
}
export type AvoSafeDeployedWithVersionEvent = TypedEvent<
  [string, string, string],
  AvoSafeDeployedWithVersionEventObject
>;

export type AvoSafeDeployedWithVersionEventFilter =
  TypedEventFilter<AvoSafeDeployedWithVersionEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface AvoFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AvoFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    avoMultiSafeBytecode(overrides?: CallOverrides): Promise<[string]>;

    avoMultisigImpl(overrides?: CallOverrides): Promise<[string]>;

    avoSafeBytecode(overrides?: CallOverrides): Promise<[string]>;

    avoSafeCreationCode(overrides?: CallOverrides): Promise<[string]>;

    avoVersionsRegistry(overrides?: CallOverrides): Promise<[string]>;

    avoWalletImpl(overrides?: CallOverrides): Promise<[string]>;

    computeAddress(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string] & { computedAddress_: string }>;

    computeAddressMultisig(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string] & { computedAddress_: string }>;

    deploy(
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployMultisig(
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployMultisigWithVersion(
      owner_: PromiseOrValue<string>,
      avoMultisigVersion_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deployWithVersion(
      owner_: PromiseOrValue<string>,
      avoWalletVersion_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isAvoSafe(
      avoSafe_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setAvoMultisigImpl(
      avoMultisigImpl_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAvoWalletImpl(
      avoWalletImpl_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  avoMultiSafeBytecode(overrides?: CallOverrides): Promise<string>;

  avoMultisigImpl(overrides?: CallOverrides): Promise<string>;

  avoSafeBytecode(overrides?: CallOverrides): Promise<string>;

  avoSafeCreationCode(overrides?: CallOverrides): Promise<string>;

  avoVersionsRegistry(overrides?: CallOverrides): Promise<string>;

  avoWalletImpl(overrides?: CallOverrides): Promise<string>;

  computeAddress(
    owner_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  computeAddressMultisig(
    owner_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  deploy(
    owner_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployMultisig(
    owner_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployMultisigWithVersion(
    owner_: PromiseOrValue<string>,
    avoMultisigVersion_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deployWithVersion(
    owner_: PromiseOrValue<string>,
    avoWalletVersion_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isAvoSafe(
    avoSafe_: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setAvoMultisigImpl(
    avoMultisigImpl_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAvoWalletImpl(
    avoWalletImpl_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    avoMultiSafeBytecode(overrides?: CallOverrides): Promise<string>;

    avoMultisigImpl(overrides?: CallOverrides): Promise<string>;

    avoSafeBytecode(overrides?: CallOverrides): Promise<string>;

    avoSafeCreationCode(overrides?: CallOverrides): Promise<string>;

    avoVersionsRegistry(overrides?: CallOverrides): Promise<string>;

    avoWalletImpl(overrides?: CallOverrides): Promise<string>;

    computeAddress(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    computeAddressMultisig(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    deploy(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployMultisig(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployMultisigWithVersion(
      owner_: PromiseOrValue<string>,
      avoMultisigVersion_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    deployWithVersion(
      owner_: PromiseOrValue<string>,
      avoWalletVersion_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(overrides?: CallOverrides): Promise<void>;

    isAvoSafe(
      avoSafe_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setAvoMultisigImpl(
      avoMultisigImpl_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAvoWalletImpl(
      avoWalletImpl_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AvoMultiSafeDeployed(address,address)"(
      owner?: PromiseOrValue<string> | null,
      avoMultiSafe?: PromiseOrValue<string> | null
    ): AvoMultiSafeDeployedEventFilter;
    AvoMultiSafeDeployed(
      owner?: PromiseOrValue<string> | null,
      avoMultiSafe?: PromiseOrValue<string> | null
    ): AvoMultiSafeDeployedEventFilter;

    "AvoMultiSafeDeployedWithVersion(address,address,address)"(
      owner?: PromiseOrValue<string> | null,
      avoMultiSafe?: PromiseOrValue<string> | null,
      version?: PromiseOrValue<string> | null
    ): AvoMultiSafeDeployedWithVersionEventFilter;
    AvoMultiSafeDeployedWithVersion(
      owner?: PromiseOrValue<string> | null,
      avoMultiSafe?: PromiseOrValue<string> | null,
      version?: PromiseOrValue<string> | null
    ): AvoMultiSafeDeployedWithVersionEventFilter;

    "AvoSafeDeployed(address,address)"(
      owner?: PromiseOrValue<string> | null,
      avoSafe?: PromiseOrValue<string> | null
    ): AvoSafeDeployedEventFilter;
    AvoSafeDeployed(
      owner?: PromiseOrValue<string> | null,
      avoSafe?: PromiseOrValue<string> | null
    ): AvoSafeDeployedEventFilter;

    "AvoSafeDeployedWithVersion(address,address,address)"(
      owner?: PromiseOrValue<string> | null,
      avoSafe?: PromiseOrValue<string> | null,
      version?: PromiseOrValue<string> | null
    ): AvoSafeDeployedWithVersionEventFilter;
    AvoSafeDeployedWithVersion(
      owner?: PromiseOrValue<string> | null,
      avoSafe?: PromiseOrValue<string> | null,
      version?: PromiseOrValue<string> | null
    ): AvoSafeDeployedWithVersionEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;
  };

  estimateGas: {
    avoMultiSafeBytecode(overrides?: CallOverrides): Promise<BigNumber>;

    avoMultisigImpl(overrides?: CallOverrides): Promise<BigNumber>;

    avoSafeBytecode(overrides?: CallOverrides): Promise<BigNumber>;

    avoSafeCreationCode(overrides?: CallOverrides): Promise<BigNumber>;

    avoVersionsRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    avoWalletImpl(overrides?: CallOverrides): Promise<BigNumber>;

    computeAddress(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    computeAddressMultisig(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deploy(
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployMultisig(
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployMultisigWithVersion(
      owner_: PromiseOrValue<string>,
      avoMultisigVersion_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deployWithVersion(
      owner_: PromiseOrValue<string>,
      avoWalletVersion_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isAvoSafe(
      avoSafe_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAvoMultisigImpl(
      avoMultisigImpl_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAvoWalletImpl(
      avoWalletImpl_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    avoMultiSafeBytecode(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    avoMultisigImpl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    avoSafeBytecode(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    avoSafeCreationCode(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    avoVersionsRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    avoWalletImpl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    computeAddress(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    computeAddressMultisig(
      owner_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deploy(
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployMultisig(
      owner_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployMultisigWithVersion(
      owner_: PromiseOrValue<string>,
      avoMultisigVersion_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deployWithVersion(
      owner_: PromiseOrValue<string>,
      avoWalletVersion_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isAvoSafe(
      avoSafe_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAvoMultisigImpl(
      avoMultisigImpl_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAvoWalletImpl(
      avoWalletImpl_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
